[package]
name = "nbs-rust"
version = "0.1.0"
authors = ["KNSN92"]
description = "A Rust library for IO and rendering audio of .nbs files."
edition = "2024"

[features]
audio = ["lru", "rubato", "symphonia"]
midi = []
zip = ["dep:zip"]

[dependencies]
byteorder = "1.5.0"
lru = { version = "0.18.0", optional = true }
rubato = { version = "2.0.0", optional = true }
symphonia = { version = "0.5.5", optional = true }
thiserror = "2.0.18"
zip = { version = "0.6.6", optional = true }
